# Generated by Django 4.0.3 on 2022-03-31 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('A', 'Admin')], default='S', max_length=1),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('stud', models.IntegerField()),
                ('status', models.CharField(choices=[('Rd', 'Received'), ('IP', 'In process'), ('Fd', 'Finished'), ('RR', 'Ready for receive')], default='Rd', max_length=2)),
                ('edu_form', models.CharField(choices=[('F', 'Full-time'), ('P', 'Part-time'), ('D', 'Distance')], max_length=1)),
                ('location', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=100)),
                ('pickup_method', models.CharField(choices=[('S', 'Self'), ('D', 'PostDelivery')], max_length=1)),
                ('organization_for', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.CheckConstraint(check=models.Q(('stud__range', (100000, 999999))), name='stud_num_is_valid'),
        ),
    ]
